### ISSUE TITLE
.ci-output.py script is broken

### ISSUE THREAD

**Issue by ajelinski** [litex-hub/litex-conda-ci#15]
Using the script will be disabled because currently it does more harm than good.

This script was intended to make log analyzing easier. Unfortunately in many cases it hides crucial information from being printed in the log, e.g. https://github.com/litex-hub/litex-conda-eda/pull/63/checks?check_run_id=1901771647#step:3:4365
```
  
  .
      |
  
  .
      |                  ^^^^^^^^^^^^^^
  
  .
     Compiling atty v0.2.14
     Compiling cast v0.2.3
  
  ..
  Some errors have detailed explanations: E0034, E0308.
  For more information about an error, try `rustc --explain E0034`.
  
  ..
  To learn more, run the command again with --verbose.
  
  ..
  Traceback (most recent call last):
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/bin/conda-build", line 11, in <module>
      sys.exit(main())
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 474, in main
      execute(sys.argv[1:])
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 465, in execute
      verify=args.verify, variants=args.variants)
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
      variants=variants
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/lib/python3.7/site-packages/conda_build/build.py", line 3005, in build_tree
      notest=notest,
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/lib/python3.7/site-packages/conda_build/build.py", line 2126, in build
      cwd=src_dir, stats=build_stats)
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/lib/python3.7/site-packages/conda_build/utils.py", line 410, in check_call_env
      return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
    File "/home/runner/work/litex-conda-eda/litex-conda-eda/workdir/conda-env/lib/python3.7/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
      raise subprocess.CalledProcessError(proc.returncode, _args)
```

**Comment by umarcor** [comment]
Should this be closed since https://github.com/litex-hub/litex-conda-ci/commit/885276d465cc649ae7d802c77510d2e6320dd93e was pushed already?
